CREATE USER PRY2205_S4 
IDENTIFIED BY "PRY2205.semana_4"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_S4;

GRANT RESOURCE TO PRY2205_S4;

ALTER USER PRY2205_S4 DEFAULT ROLE RESOURCE;