--CASOS

--CASO 1: LISTADO DE TRABAJADORES
-- EL OBJETIVO ES CREAR UN LISTADO DE TRABAJADORES CON UN FORMATO ESPECIFICO, UNIENDO INFORMACION DE SUS TABLAS DE TIPO
-- Y CIUDAD FILTRANDOLOS POR UN RANDO DE SUELDO

SELECT
    -- SE CONCATENAN TANTO EL NOMBRE Y APELLIDOS EN MAYUSCULA Y SE FORMATEA EL NOMBRE DE LA TABLA SEMEJANTE A LA IMAGEN 2
    UPPER(t.nombre || ' ' || t.appaterno || ' ' || t.apmaterno) AS "Nombre Completo Trabajador",
    -- RUT CON FORMATO, SE FORMATEA EL NOMBRE DE LA COLUMNA SEMEANTE A LA FIGURA 2
    TO_CHAR(t.numrut, 'FM99G999G990', 'NLS_NUMERIC_CHARACTERS = '',.''') || '-' || t.dvrut AS "RUT Trabajador",
    -- TIPO DE TRABAJAADOR CON SU NOMBRE FORMATEADO SEMEJANTE AL DE LA IMAGEN 2, EN MAYUSCULA
    UPPER(tt.desc_categoria)AS "Tipo Trabajador",
    --NOMBRE DE CIUDAD EN MAYUSCULA, FORMATEANDO NOMBRE SEMEJANTE A LA FIG 2
    UPPER(c.nombre_ciudad) AS "Ciudad Trabajador",
    --SE FORMATEA EL SUELDO BASE, Y EL NOMBRE DE LA COLUMNA
    TO_CHAR(t.sueldo_base, 'FML999G999G990', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = ''.,''') AS "Sueldo Base"
-- DESDE LA TABLA TRABAJADAOR CON UN ALIAS MAS CORTO 
FROM
    TRABAJADOR t
-- COMO SE NECESITAN DATOS DE 3 TABLAS (TRABAJADOR, TIPO TRABAJADOR Y CIUDAD TRABAJADOR)SE UNE TRABAJADOR CON TIPO TRABAJADOR USANDO LA LLAVE ID_CATEGORIA_T
JOIN
    TIPO_TRABAJADOR tt ON t.id_categoria_t = tt.id_categoria
--SE UNE TRABAJADOR CON COMUNA_CIUDAD USANDO LA LLAVE ID_CIUDAD
JOIN
    COMUNA_CIUDAD c ON t.id_ciudad = c.id_ciudad
-- SOLO AQUELLOS TRABAJADORRES QUE EL SUELDO BASE ESTE ENTRE 650 MIL Y 3 MILLONES
WHERE
    t.sueldo_base BETWEEN 650000 AND 3000000
-- SE ORDENA LA INFORMACION CON LA CIUDAD DEL TRABAJADOR EN FORMA DESCENDENTE Y EL SUELDO EN FORMA ASCENDENTE    
ORDER BY
    "Ciudad Trabajador" DESC,
    t.sueldo_base ASC;



--CASO 2: LISTADO CAJEROS
--OBJETIVO:  CREAR UN REPORTE QUE LISTE SOLO LOS TRABAJADORES CON ROL "CAJERO", CALCULANDO EL TOTAL DE TICKETS QUE HAN VENDIDO, EL MOTO TOTAL DE ESAS VENTAS,
-- Y LA COMISION TOTAL GENERADA. aDEMAS, DEBE FILTRAR PARA MOSTRAR SOLO A LOS CAJEROS CUYO TOTAL VENDIDO SUPERE LOS 50MIL

SELECT
    --NUMERO DE RUT CON FORMATO, Y FORMATEANDO SU ALIAS CORRESPONDIENTE. DESDE LA TABLA TRABAJADOR t
    TO_CHAR(t.numrut,  'FML999G999G990', 'NLS_CURRENCY = '' '' NLS_NUMERIC_CHARACTERS = '',.''') || '-' || t.dvrut AS "RUT Trabajador",
    --CONCATENAMOS EL NOMBRE DEL TRABAJADOR, CON LA PRIMERA MINUSCULA EL RESTO MAYUSCULA, CON EL APELLIDO PATERNO TODO EN MAYUSCULA Y SU ALIAS CORRESPONDIENTE
    INITCAP(t.nombre) || ' ' || UPPER (t.appaterno) AS "Nombre Trabajador",
    -- CONTAMOS LA CANTIDAD DE TICKETS VENDIDOS Y SE EXTRAE LA INFORMACION DESDE LA TABLA TICKETS_CONCIERTO. SE FORMATEA EL ALIAS AL CORRESPONDIENTE
    COUNT(tk.nro_ticket) AS "Total Tickets",
    -- SE SUMA EL TOTAL VENDIDO DE CADA TRABAJADOR, SE FORMATEA CON FORMATO EXCLUSIVO, SE DEJA TODO EL FORMATO TEXTO A LA DERECHA RELLENANDO CON ESPACIOS EN BLANCO LO FALTANTE PARA COMPLETAS LOS DIGITOS, SE FORMATEA EL ALIAS
    -- SE EXTRAE LA INFORMACION DESDE TICKETS_CONCIERTO
    LPAD(TO_CHAR(SUM(tk.monto_ticket),'FML999G999G990', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = '',.'''),12) AS "Total Vendido", 
    --SE SUMA LA COMISION DE CADA TICKET VENDIDOPOR EL TRABAJADOR Y SE DEJA CON FORMATO EXCLUSIVO, 
    --TODO HACIA LA DERECHA, COMO EN LA IMAGEN REFERENCIAL, SE FORMATEA EL ALIAS CORRESPODIENTE. 
    --SE EXTRAE INFORMACION DE LA TABLA COMISIONES_TICKET
    LPAD(TO_CHAR(SUM(ct.valor_comision),'FML999G999G990', 'NLS_CURRENCY = ''$'' NLS_NUMERIC_CHARACTERS = '',.'''),12) AS "Comision Total",
    --EN MAYUSCULA SE FORMATEA EL ALIAS DE LA DESCRIPCION DE CADA CATEGORIA DE TRABAJADOR
    --SE EXTRAE LA INFORMACION DESDE TIPO_TRABAJADOR
    UPPER(tt.desc_categoria) AS "Tipo Trabajador",
    --TODO EN MAYUSCULA SE EXTRAE INFORMACION DE LA TABLA COMUNA_CIUDAD, FORMATEANDO EL ALIAS
    UPPER(c.nombre_ciudad) AS "Ciudad Trabajador"
--SE OBTIENE LA INFORMACION DESDE TRABAJADOR, SE FORMATEA EL ALIAS MAS CORTO "t"
FROM
    TRABAJADOR t
--SE UNE TIPO_TRABAJADOR CON  TRABAJADOR USANDO LA CLAVE FORANEA id_categoria_t. PARA OBTENER LA DESC_CATEGORIA  
JOIN 
    TIPO_TRABAJADOR tt ON t.id_categoria_t = tt.id_categoria
-- SE UNE COMUNA_CIUDAD CON TRABAJADOR CON LA CLAVE FORANEA id_ciudad PARA OBTENER EL NOMBRE LA CIUDAD DEL TRABAJADOR
JOIN 
    COMUNA_CIUDAD c ON t.id_ciudad = c.id_ciudad
-- SE UNE TICKETS_CONCERTOS CON TRABAJADOR. CON LA CLAVE FORANEA numrut PARA OBTENER CUANDOS TICKETS VENDIDOS TIENE CADA TRABAJADOR
JOIN
    TICKETS_CONCIERTO tk ON t.numrut = tk.numrut_t
--SE UNE COMISIONES TICKETS CON TICKETS_CONCIERTO CON LA CLAVE FORANEA nro_ticket PARA OBTENER EL VALOR DE LA COSIMION POR CADA TICKET VENDIDO
JOIN
    COMISIONES_TICKET ct ON tk.nro_ticket = ct.nro_ticket
--FILTRAMOS SOLAMENTE A LOS TRABAJADORES CON DESC_CATEGORIA COMO CAJERO EN MAYUSCULA
WHERE
    UPPER(tt.desc_categoria) = 'CAJERO'
-- COMO SE UTILIZAN FUNCIONES DE AGREGACION COMO COUNT O SUM, DEBEMOS AGRUPAR TODAS LAS COLUMNAS QUE NO SON AGREGADAS,
--AGRUPAMOS POR LOS DATOS DEL TRABAJADOR, PARA PSEUDO COLAPSAR TODOS SUS TICKETS VENDIDOS EN UNA SOLA FILA DE RESULTADO
GROUP BY
    t.numrut, t.dvrut, t.nombre, t.appaterno, tt.desc_categoria, c.nombre_ciudad
--FILTROS DE FRUPOS: ELIMINA CUALQUIER CAJERO QUE COMO RESULTADO DE EL TOTAL DE TICKETS VENDIDOS (SUM )NO SUPERE LOS 50000
HAVING
    SUM(tk.monto_ticket) > 50000
-- SE ORDENA LA TABLA POR EL TOTAL VENDIDO, DE MAYOR A MENOR.
ORDER BY
    SUM(tk.monto_ticket) DESC;
    

--CASO 3: LISTADO DE BONIFICACIONES
--OBJETIVO: SABER EL AÑO DE INGRESO DE CADA TRABAJADOR PARA OBTENER SU ANTIGUEDAD, SABER SI CUENTA CON ASIGNACION FAMILIAR A TRAVES DE CARGAS FAMILIARES
--OBTENER SU SISTEMA PREVISIONA.
--TODO PARA DECRETAR LA POSIBILIDAD DE BONOS POR ANTIGUEDAD
    
    
    
    
    
    